#======================================Iteration 2=============================
#clean the data
# library(zoo)
# WBDrn=na.ma(WBD[3:14])
# WBDrn=cbind(WBD[1:5576,1:2],WBDrn)
# install.packages("imputeTS")
library(imputeTS)
WBD[WBD==".."] = "NA"
WBDp=WBD[1:5576,3:14]
WBDt=t(WBDp)
# WBDt=as.numeric(WBDt)
# WBDt=as.matrix(WBDt)
# WBDt=matrix(WBDt,12, byrow = TRUE)

# i = 1:5576
#linear interpulation
WBDrn=na.ma(WBDt, weighting = "linear")
WBDrnt=t(WBDrn)
#fill the left row mean
k <- which(is.na(WBDrnt), arr.ind=TRUE)
WBDrnt[k] <- rowMeans(WBDrnt, na.rm=TRUE)[k[,1]]
WBDtdf=data.frame(WBDrnt)
WBD=cbind(WBD[1:5576,1:2],WBDtdf)
summary(WBD)
colnames(WBD)= c("Variable", "countryName","1990","2000","2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017")
write.table(WBD, file = "FillLplusRM.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
#---------------------------------------
#----------------------------1990-----------------------------------------------------------
#select the new df separated by each year column
WBD1990 = WBD[,1:3]
#reshape the dataframe into wide format
WBD1990w = reshape(WBD1990, idvar = "countryName", timevar = "Variable",direction = "wide")
#remove the quote and blanks from the data region
WBD1990w = WBD1990w[1:82,1:69]
# change the weird dot by the null content(Already moved to WBD for efficiency)
# WBD1990w[WBD1990w==".."] = ""
#remove some weird 0 generated by World Bank database system
index = which(WBD1990w[,11] == "" | WBD1990w[,12] == "")
WBD1990w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out1990 = WBD1990w[, remainCol]
#export the csv file
write.table(Out1990, file = "WBD1990F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
#export an short colname version
colnames(Out1990)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
write.table(Out1990, file = "SN1990F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
# test = unique(WBD1990w[, 2])
# sort(summary(test))
#-----------------------------------2000-----------------------------------------------------------------
WBD2000 = WBD[,c(1,2,4)]
WBD2000w = reshape(WBD2000, idvar = "countryName", timevar = "Variable",direction = "wide")
WBD2000w = WBD2000w[1:82,1:69]
# test = unique(WBD2000w[, 2])
# sort(summary(test))
#remove some weird 0 generated by World Bank database system
index = which(WBD2000w[,11] == "" | WBD2000w[,12] == "")
WBD2000w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out2000 = WBD2000w[, remainCol]
#export the csv file
write.table(Out2000, file = "WBD2000F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
colnames(Out2000)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
summary(Out2000)
write.table(Out2000, file = "SN2000F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
#------------------------------------2008------------------------------------------------------------------
WBD2008 = WBD[,c(1,2,5)]
WBD2008w = reshape(WBD2008, idvar = "countryName", timevar = "Variable",direction = "wide")
WBD2008w = WBD2008w[1:82,1:69]
#remove some weird 0 generated by World Bank database system
index = which(WBD2008w[,11] == "" | WBD2008w[,12] == "")
WBD2008w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out2008 = WBD2008w[, remainCol]
#export the csv file
write.table(Out2008, file = "WBD2008F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
colnames(Out2008)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
summary(Out2008)
write.table(Out2008, file = "SN2008F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")

# test = unique(WBD2008w[, 2])
# sort(summary(test))

#----------------------------------------2009--------------------------------------------------------------------
WBD2009 = WBD[,c(1,2,6)]
WBD2009w = reshape(WBD2009, idvar = "countryName", timevar = "Variable",direction = "wide")
WBD2009w = WBD2009w[1:82,1:69]
test = unique(WBD2009w[, 2])
sort(summary(test))

#remove some weird 0 generated by World Bank database system
index = which(WBD2009w[,11] == "" | WBD2009w[,12] == "")
WBD2009w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out2009 = WBD2009w[, remainCol]
#export the csv file
write.table(Out2009, file = "WBD2009F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
colnames(Out2009)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
summary(Out2009)
write.table(Out2009, file = "SN2009F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
#-----------------------------------------2010----------------------------------------------------------


WBD2010 = WBD[,c(1,2,7)]
WBD2010w = reshape(WBD2010, idvar = "countryName", timevar = "Variable",direction = "wide")
WBD2010w = WBD2010w[1:82,1:69]
test = unique(WBD2010w[, 2])
sort(summary(test))

#remove some weird 0 generated by World Bank database system
index = which(WBD2010w[,11] == "" | WBD2010w[,12] == "")
WBD2010w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out2010 = WBD2010w[, remainCol]
#export the csv file
write.table(Out2010, file = "WBD2010F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
colnames(Out2010)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
summary(Out2010)
write.table(Out2010, file = "SN2010F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")

#----------------------------------------------2011---------------------------------------------------

WBD2011 = WBD[,c(1,2,8)]
WBD2011w = reshape(WBD2011, idvar = "countryName", timevar = "Variable",direction = "wide")
WBD2011w = WBD2011w[1:82,1:69]
test = unique(WBD2011w[, 2])
sort(summary(test))
#remove some weird 0 generated by World Bank database system
index = which(WBD2011w[,11] == "" | WBD2011w[,12] == "")
WBD2011w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out2011 = WBD2011w[, remainCol]
#export the csv file
write.table(Out2011, file = "WBD2011F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
colnames(Out2011)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
summary(Out2011)
write.table(Out2011, file = "SN2011F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")

#----------------------------------------------2012---------------------------------------------------
WBD2012 = WBD[,c(1,2,9)]
WBD2012w = reshape(WBD2012, idvar = "countryName", timevar = "Variable",direction = "wide")
WBD2012w = WBD2012w[1:82,1:69]
test = unique(WBD2012w[, 2])
sort(summary(test))
#remove some weird 0 generated by World Bank database system
index = which(WBD2012w[,11] == "" | WBD2012w[,12] == "")
WBD2012w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out2012 = WBD2012w[, remainCol]
#export the csv file
write.table(Out2012, file = "WBD2012F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
colnames(Out2012)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
summary(Out2012)
write.table(Out2012, file = "SN2012F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
#----------------------------------------------2013---------------------------------------------------
WBD2013 = WBD[,c(1,2,10)]
WBD2013w = reshape(WBD2013, idvar = "countryName", timevar = "Variable",direction = "wide")
WBD2013w = WBD2013w[1:82,1:69]
test = unique(WBD2013w[, 2])
sort(summary(test))
#remove some weird 0 generated by World Bank database system
index = which(WBD2013w[,11] == "" | WBD2013w[,12] == "")
WBD2013w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out2013 = WBD2013w[, remainCol]
#export the csv file
write.table(Out2013, file = "WBD2013F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
colnames(Out2013)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
summary(Out2013)
write.table(Out2013, file = "SN2013F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
#----------------------------------------------2014---------------------------------------------------
WBD2014 = WBD[,c(1,2,11)]
WBD2014w = reshape(WBD2014, idvar = "countryName", timevar = "Variable",direction = "wide")
WBD2014w = WBD2014w[1:82,1:69]
test = unique(WBD2014w[, 2])
sort(summary(test))
#remove some weird 0 generated by World Bank database system
index = which(WBD2014w[,11] == "" | WBD2014w[,12] == "")
WBD2014w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out2014 = WBD2014w[, remainCol]
#export the csv file
write.table(Out2014, file = "WBD2014F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
colnames(Out2014)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
summary(Out2014)
write.table(Out2014, file = "SN2014F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
#----------------------------------------------2015---------------------------------------------------
WBD2015 = WBD[,c(1,2,12)]
WBD2015w = reshape(WBD2015, idvar = "countryName", timevar = "Variable",direction = "wide")
WBD2015w = WBD2015w[1:82,1:69]
test = unique(WBD2015w[, 2])
sort(summary(test))
#remove some weird 0 generated by World Bank database system
index = which(WBD2015w[,11] == "" | WBD2015w[,12] == "")
WBD2015w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out2015 = WBD2015w[, remainCol]
#export the csv file
write.table(Out2015, file = "WBD2015F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
colnames(Out2015)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
summary(Out2015)
write.table(Out2015, file = "SN2015F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
#----------------------------------------------2016---------------------------------------------------
WBD2016 = WBD[,c(1,2,13)]
WBD2016w = reshape(WBD2016, idvar = "countryName", timevar = "Variable",direction = "wide")
WBD2016w = WBD2016w[1:82,1:69]
test = unique(WBD2016w[, 2])
sort(summary(test))
#remove some weird 0 generated by World Bank database system
index = which(WBD2016w[,11] == "" | WBD2016w[,12] == "")
WBD2016w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out2016 = WBD2016w[, remainCol]
#export the csv file
write.table(Out2016, file = "WBD2016F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
colnames(Out2016)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
summary(Out2016)
write.table(Out2016, file = "SN2016F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
#----------------------------------------------2017---------------------------------------------------
WBD2017 = WBD[,c(1,2,14)]
WBD2017w = reshape(WBD2017, idvar = "countryName", timevar = "Variable",direction = "wide")
WBD2017w = WBD2017w[1:82,1:69]
test = unique(WBD2017w[, 2])
sort(summary(test))
#remove some weird 0 generated by World Bank database system
index = which(WBD2017w[,11] == "" | WBD2017w[,12] == "")
WBD2017w[index, 10] = ""
remainCol <- c(1,2,4,9,11,12,15:18,21,35:53,63:65)
Out2017 = WBD2017w[, remainCol]
#export the csv file
write.table(Out2017, file = "WBD2017F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
colnames(Out2017)<-c("CN",	"GDP",	"FDINI", "NFA",	"GDPg",	"GDPpcg",	"GCaFg",	"Ind1",	"ind2",	"Ser",	"ExGSgp",	
                     "ADRold",	"ADRyoun",	"PPg",	"PPf",	"PPm",	"PP1519f",	"PP1519m",	"PP2024f",	"PP2024m",	
                     "PP2529m",	"PP2529f",	"PP65above",	"PP65afnum",	"PP65af",	"PP1564m",	"PP1564f",	"Lab1524f",	
                     "Lab1524m",	"Lab1524tot",	"Labf",	"Labtot",	"RFtoMlabpartcp")
summary(Out2017)
write.table(Out2017, file = "SN2017F.csv", row.names = FALSE, col.names = TRUE, na = "", sep=",")
